# Generated by Django 5.2.17 on 2026-08-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_resena_delete_reseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
