# Generated by Django 6.1 on 2026-08-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_alter_resena_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
