# Generated by Django 5.2.17 on 2026-09-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0006_alter_resena_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
