# Generated by Django 5.2.17 on 2026-09-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_movimiento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
