# Generated by Django 6.1.1 on 2026-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_alter_movimiento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario_caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('comentario', models.TextField(max_length=500)),
            ],
        ),
    ]
