# Generated by Django 5.2.17 on 2026-08-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_id'),
        ('usuarios', '0005_remove_usuario_apellido_remove_usuario_usuario'),
    ]

    operations = [
    ]
