# Generated by Django 6.0.6 on 2026-07-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='categoria',
            field=models.CharField(default='plato_fuerte', max_length=50),
        ),
        migrations.AddField(
            model_name='plato',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
