# Generated by Django 6.1 on 2026-08-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_plato_categoria_plato_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
    ]
