# Generated by Django 5.2.17 on 2026-08-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_plato_categoria_plato_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
