# Generated by Django 5.2.17 on 2026-08-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_plato_id'),
        ('menu', '0003_plato_imagen'),
    ]

    operations = [
    ]
