# Generated by Django 6.1 on 2026-08-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_merge_0003_alter_plato_id_0003_plato_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
