# Generated by Django 6.1 on 2026-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_plato_categoria_alter_plato_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
