# Generated by Django 6.1 on 2026-09-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_plato_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plato',
        ),
    ]
