# Generated by Django 6.1 on 2026-08-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_mesa_zona_alter_reserva_estado_alter_reserva_mesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='zona',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Zona',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
