# Generated by Django 6.1 on 2026-08-26 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_mesa_zona_alter_reserva_mesa_delete_zona_and_more'),
        ('usuarios', '0004_usuario_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='telefono',
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.CharField(blank=True, default='Por asignar', max_length=50, null=True),
        ),
    ]
