# Generated by Django 5.2.17 on 2026-08-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_id'),
        ('reservas', '0006_remove_reserva_nombre_remove_reserva_telefono_and_more'),
    ]

    operations = [
    ]
