# Generated by Django 6.1.1 on 2026-09-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_plato_categoria_plato_destacado_plato_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('entradas', 'Entradas'), ('platos_fuertes', 'Platos Fuertes'), ('bebidas', 'Bebidas'), ('postres', 'Postres'), ('otros', 'Otros')], default='platos_fuertes', max_length=50),
        ),
        migrations.AlterField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
