# Generated by Django 6.1.1 on 2026-09-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_remove_plato_destacado_remove_plato_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
    ]
