# Generated by Django 5.2.17 on 2026-09-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_alter_consumomesa_id_alter_mesa_id_alter_plato_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='forma',
            field=models.CharField(choices=[('redonda', 'Redonda'), ('cuadrada', 'Cuadrada'), ('rectangular', 'Rectangular')], default='cuadrada', max_length=20),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='posicion_x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='posicion_y',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='reservas.zona'),
        ),
    ]
